version: '3'
services:
  server:
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
      - ./data:/data
    links:
      - mongo
      - redis
    depends_on:
      - redis
      - mongo

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=image-detector
      - AUTH_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - AUTH_ALGORITHM=HS256
      - AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=120

  training:
    build:
      dockerfile: Dockerfile
      context: ./training
    restart: always
    volumes:
      - ./training:/app
      - ./data:/data
    links:
      - mongo
      - redis
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=image-detector

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis


